### ISSUE TITLE
Нужно всё-таки сделать ещё одну функцию, которая принимает все параметры и выдаёт финальное значение

### ISSUE THREAD

**Issue by coursar** [DamirZaripov16/JavaScript2018#2]
https://github.com/DamirZaripov16/JavaScript2018/blob/3f760573af6444741e8aa0e03672bacd79211d20/wallpaper/app/wallpaper.js#L22-L27

**Comment by DamirZaripov16** [comment]
Исправлено в отдельном репозитории: https://github.com/DamirZaripov16/wallpaper
