### ISSUE TITLE
Этот явно попал не совсем туда

### ISSUE THREAD

**Issue by coursar** [DamirZaripov16/JavaScript2018#3]
https://github.com/DamirZaripov16/JavaScript2018/blob/3f760573af6444741e8aa0e03672bacd79211d20/gas/app/wallpaper.js#L1-L27

**Comment by DamirZaripov16** [comment]
Исправлено в отдельном репозитории : https://github.com/DamirZaripov16/gas

**Comment by coursar** [comment]
Если сделали таску - закрывайте. Репозиторий можно удалить.
